services:
  - type: web
    name: calle-receiver
    runtime: docker
    rootDir: apps/python/calle-receiver
    plan: free
    envVars:
      - key: TWILIO_NUMBER
        sync: false
      - key: FORWARD_TO
        sync: false
      - key: DASHBOARD_PASSWORD
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: PUBLIC_BASE_URL
        sync: false
